# /usr/share/logstash/config/pipelines.yml
- pipeline.id: nginx
  path.config: "/usr/share/logstash/pipeline/nginx.conf"
  pipeline.workers: 2

- pipeline.id: app-logs
  path.config: "/usr/share/logstash/pipeline/app-logs.conf"
  pipeline.workers: 2

- pipeline.id: syslog
  path.config: "/usr/share/logstash/pipeline/syslog.conf"
  pipeline.workers: 1